In [1]:
%load_ext dotenv
%dotenv

# What are we doing?

## Objectives 


* Build a data pipeline that downloads price data from the internet, stores it locally, transforms it into return data, and stores the feature set.
    - Getting the data.
    - Schemas and index in dask.

* Explore the parquet format.
    - Reading and writing parquet files.
    - Read datasets that are stored in distributed files.
    - Discuss dask vs pandas as a small example of big vs small data.
    
* Discuss the use of environment variables for settings.
* Discuss how to use Jupyter notebooks and source code concurrently. 
* Logging and using a standard logger.

## About the Data

+ We will download the prices for a list of stocks.
+ The source is Yahoo Finance and we will use the API provided by the library yfinance.


## Medallion Architecture

+ The architecture that we are thinking about is called Medallion by [DataBricks](https://www.databricks.com/glossary/medallion-architecture). It is an ELT type of thinking, although our data is well-structured.

![Medallion Architecture (DataBicks)](./images/02_medallion_architecture.png)

+ In our case, we would like to optimize the number of times that we download data from the internet. 
+ Ultimately, we will build a pipeline manager class that will help us control the process of obtaining and transforming our data.

![](./images/02_target_pipeline_manager.png)

# Download Data

Download the [Stock Market Dataset from Kaggle](https://www.kaggle.com/datasets/jacksoncrow/stock-market-dataset). Note that you may be required to register for a free account.

Extract all files into the directory: `./05_src/data/prices_csv/`

Your folder structure should include the following paths:

+ `05_src/data/prices_csv/etfs`
+ `05_src/data/prices_csv/stocks`

In [2]:
import pandas as pd
import os
import sys
from glob import glob

In [3]:
sys.path.append(os.getenv('SRC_DIR'))
from utils.logger import get_logger
_logs=get_logger(__name__)

A few things to notice in the code chunk above:

+ Libraries are ordered from high-level to low-level libraries from the package manager (pip in this case, but could be conda, poetry, etc.)
+ The command `sys.path.append("../05_src/)` will add the `../05_src/` directory to the path in the Notebook's kernel. This way, we can use our modules as part of the notebook.
+ Local modules are imported at the end. 
+ The function `get_logger()` is called with `__name__` as recommended by the documentation.

Now, to load the historical price data for stocks and ETFs, we could use:

In [4]:
import random
random.seed(42)
stock_csvs=glob(os.path.join(os.getenv('SRC_DIR'),"data","prices_csv","stocks","*.csv"))
sample_stock_csvs=random.sample(stock_csvs,60)

In [5]:
df_list=[]
for file_path in sample_stock_csvs:
    df=pd.read_csv(file_path)
    df=df.assign(
        file_name=os.path.basename(file_path),
        ticker=os.path.basename(file_path).replace(".csv",""),
        Date=pd.to_datetime(df['Date'])
    )
    df_list.append(df)
    
combined_df=pd.concat(df_list,ignore_index=True)

Verify the structure of the `stock_prices` data:

In [6]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 239659 entries, 0 to 239658
Data columns (total 9 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Date       239659 non-null  datetime64[ns]
 1   Open       239656 non-null  float64
 2   High       239656 non-null  float64
 3   Low        239656 non-null  float64
 4   Close      239656 non-null  float64
 5   Adj Close  239656 non-null  float64
 6   Volume     239656 non-null  float64
 7   file_name  239659 non-null  object
 8   ticker     239659 non-null  object
dtypes: datetime64[ns](1), float64(6), object(2)
memory usage: 16.5+ MB

We can subset our ticker data set using standard indexing techniques. A good reference for this type of data manipulation is Panda's [Documentation](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-and-selecting-data) and [Cookbook](https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook-selection).

From the subset data frame, select one column and convert to list.

In [7]:
ticker_list=combined_df['ticker'].unique().tolist()

# Storing Data in CSV

+ We have some data. How do we store it?
+ We can compare two options, CSV and Parqruet, by measuring their performance:

    - Time to save.
    - Space required.

In [45]:
def get_dir_size(path='.'):
    '''Returns the total size of files contained in path.'''
    total = 0
    with os.scandir(path) as it:
        for entry in it:
            if entry.is_file():
                total += entry.stat().st_size
            elif entry.is_dir():
                total += get_dir_size(entry.path)
    return total

In [9]:
import shutil
import time

In [ ]:
csv_dir=os.path.join(os.getenv('TEMP_DATA'),"csv")
shutil.rmtree(csv_dir,ignore_errors=True)
stock_csv_path=os.path.join(csv_dir,"stocks.csv")
os.makedirs(csv_dir)

In [ ]:
start_time=time.time()
combined_df.to_csv(stock_csv_path, index = False)
end_time=time.time()

In [33]:
print(f'it took {end_time-start_time} seconds ')
print(f'csv size is {os.path.getsize(stock_csv_path)*1e-6} MB')

it took 0.8334429264068604 seconds
csv size is 26.618406999999998 MB

## Save Data to Parquet

### Dask 

We can work with with large data sets and parquet files. In fact, recent versions of pandas support pyarrow data types and future versions will require a pyarrow backend. The pyarrow library is an interface between Python and the Appache Arrow project. The [parquet data format](https://parquet.apache.org/) and [Arrow](https://arrow.apache.org/docs/python/parquet.html) are projects of the Apache Foundation.

However, Dask is much more than an interface to Arrow: Dask provides parallel and distributed computing on pandas-like dataframes. It is also relatively easy to use, bridging a gap between pandas and Spark.

In [34]:
import dask.dataframe as dd

c:\Users\Marsh\miniconda3\envs\marsham_env\lib\site-packages\dask\dataframe\_pyarrow_compat.py:15: FutureWarning: Minimal version of pyarrow will soon be increased to 14.0.1. You are using 11.0.0. Please consider upgrading.
  warnings.warn(

In [39]:
parquet_dir=os.path.join(os.getenv("TEMP_DATA"),"parquet")
shutil.rmtree(parquet_dir, ignore_errors=True)
os.makedirs(parquet_dir, exist_ok=True)

In [42]:
stock_dd=dd.from_pandas(combined_df,npartitions=len(ticker_list))

start_time=time.time()
stock_dd.to_parquet(parquet_dir)
end_time=time.time()

c:\Users\Marsh\miniconda3\envs\marsham_env\lib\site-packages\pandas\core\frame.py:717: DeprecationWarning: Passing a BlockManager to DataFrame is deprecated and will raise in a future version. Use public APIs instead.
  warnings.warn(
c:\Users\Marsh\miniconda3\envs\marsham_env\lib\site-packages\pandas\core\frame.py:717: DeprecationWarning: Passing a BlockManager to DataFrame is deprecated and will raise in a future version. Use public APIs instead.
  warnings.warn(
c:\Users\Marsh\miniconda3\envs\marsham_env\lib\site-packages\pandas\core\frame.py:717: DeprecationWarning: Passing a BlockManager to DataFrame is deprecated and will raise in a future version. Use public APIs instead.
  warnings.warn(
c:\Users\Marsh\miniconda3\envs\marsham_env\lib\site-packages\pandas\core\frame.py:717: DeprecationWarning: Passing a BlockManager to DataFrame is deprecated and will raise in a future version. Use public APIs instead.
  warnings.warn(

In [48]:
print(f'it took {end_time - start_time} seconds')
print(f'Parquet file size { get_dir_size(parquet_dir)*1e-6 } MB')

it took 3.0884017944335938 seconds
Parquet file size 9.697332 MB

### Parquet files and Dask Dataframes

+ Parquet files are immutable: once written, they cannot be modified.
+ Dask DataFrames are a useful implementation to manipulate data stored in parquets.
+ Parquet and Dask are not the same: parquet is a file format that can be accessed by many applications and programming languages (Python, R, PowerBI, etc.), while Dask is a package in Python to work with large datasets using distributed computation.
+ **Dask is not for everything** (see [Dask DataFrames Best Practices](https://docs.dask.org/en/stable/dataframe-best-practices.html)). 

    - Consider cases suchas small to large joins, where the small dataframe fits in memory, but the large one does not. 
    - If possible, use pandas: reduce, then use pandas.
    - Pandas performance tips apply to Dask.
    - Use the index: it is beneficial to have a well-defined index in Dask DataFrames, as it may speed up searching (filtering) the data. A one-dimensional index is allowed.
    - Avoid (or minimize) full-data shuffling: indexing is an expensive operations. 
    - Some joins are more expensive than others. 

        * Not expensive:

            - Join a Dask DataFrame with a pandas DataFrame.
            - Join a Dask DataFrame with another Dask DataFrame of a single partition.
            - Join Dask DataFrames along their indexes.

        * Expensive:

            - Join Dask DataFrames along columns that are not their index.

# How do we store prices?

+ We can store our data as a single blob. This can be difficult to maintain, especially because parquet files are immutable.
+ Strategy: organize data files by ticker and date. Update only latest month.

In [59]:
df_dir=os.getenv('PRICE_DATA')
shutil.rmtree(df_dir)
os.makedirs(df_dir)

In [61]:
for ticker in ticker_list:
    ticker_df=combined_df[combined_df['ticker']==ticker]
    ticker_df=ticker_df.assign(year=ticker_df.Date.dt.year)
    for y in ticker_df['year'].unique().tolist():
        ticker_df_year=ticker_df[ticker_df['year']==y]
        ticker_dd_year=dd.from_pandas(ticker_df_year,2)
        path=os.path.join(df_dir,ticker,f"{ticker}_{y}")
        ticker_dd_year.to_parquet(path)

Why would we want to store data this way?

+ Easier to maintain. We do not update old data, only recent data.
+ We can also access all files as follows.

# Load, Transform and Save

## Load

+ Parquet files can be read individually or as a collection.
+ `dd.read_parquet()` can take a list (collection) of files as input.
+ Use `glob` to get the collection of files.

In [70]:
par_files=glob(os.path.join(df_dir,"**","*.parquet"),recursive=True)
dd_stock=dd.read_parquet(par_files).set_index('ticker')

## Transform

+ This transformation step will create a *Features* data set. In our case, features will be stock returns (we obtained prices).
+ Dask dataframes work like pandas dataframes: in particular, we can perform groupby and apply operations.
+ Notice the use of [an anonymous (lambda) function](https://realpython.com/python-lambda/) in the apply statement.

In [77]:
trans_dd=dd_stock.groupby('ticker',group_keys=False).apply(lambda x : x.assign(close_lag_1=x['Close'].shift(1)))
trans_dd

C:\Users\Marsh\AppData\Local\Temp\ipykernel_18292\1254891649.py:1: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  trans_dd=dd_stock.groupby('ticker',group_keys=False).apply(lambda x : x.assign(close_lag_1=x['Close'].shift(1)))

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume file_name   year close_lag_1
npartitions=60
ACN             datetime64[ns]  float64  float64  float64  float64   float64  float64    object  int32     float64
ALDX                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...
...                        ...      ...      ...      ...      ...       ...      ...       ...    ...         ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...
Dask Name: groupbyapply, 3 expressions
Expr=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(5587b09), _other='ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x000002D9487654C0>, meta=<no_default>, args=(), kwargs={})

In [78]:
trans_dd['Change']=trans_dd['Close']-trans_dd['close_lag_1']-1

## Lazy Exection

What does `dd_rets` contain?

In [79]:
trans_dd

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume file_name   year close_lag_1   Change
npartitions=60
ACN             datetime64[ns]  float64  float64  float64  float64   float64  float64    object  int32     float64  float64
ALDX                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...      ...
...                        ...      ...      ...      ...      ...       ...      ...       ...    ...         ...      ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...      ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...       ...    ...         ...      ...
Dask Name: assign, 8 expressions
Expr=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(5587b09), _other='ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x000002D9487654C0>, meta=<no_default>, args=(), kwargs={}))

+ Dask is a lazy execution framework: commands will not execute until they are required. 
+ To trigger an execution in dask use `.compute()`.

In [80]:
trans_dd.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,file_name,year,close_lag_1,Change
ticker,,,,,,,,,,,
ACN,2001-07-19,15.10,15.29,15.00,15.17,11.404394,34994300.0,ACN.csv,2001,NaN,NaN
ACN,2001-07-20,15.05,15.05,14.80,15.01,11.284108,9238500.0,ACN.csv,2001,15.17,-1.16
ACN,2001-07-23,15.00,15.01,14.55,15.00,11.276587,7501000.0,ACN.csv,2001,15.01,-1.01
ACN,2001-07-24,14.95,14.97,14.70,14.86,11.171341,3537300.0,ACN.csv,2001,15.00,-1.14
ACN,2001-07-25,14.70,14.95,14.65,14.95,11.238999,4208100.0,ACN.csv,2001,14.86,-0.91
...,...,...,...,...,...,...,...,...,...,...,...
ZIXI,2003-06-26,4.04,4.19,3.86,4.00,4.000000,515300.0,ZIXI.csv,2003,4.04,-1.04
ZIXI,2003-06-27,4.00,4.05,3.79,3.85,3.850000,162400.0,ZIXI.csv,2003,4.00,-1.15
ZIXI,2003-06-30,3.84,4.00,3.72,3.77,3.770000,119900.0,ZIXI.csv,2003,3.85,-1.08
ZIXI,2003-07-01,3.72,3.85,3.65,3.78,3.780000,202100.0,ZIXI.csv,2003,3.77,-0.99
ZIXI,2003-07-02,3.81,3.99,3.73,3.73,3.730000,81100.0,ZIXI.csv,2003,3.78,-1.05

## Save

+ Apply transformations to calculate daily returns
+ Store the enriched data, the silver dataset, in a new directory.
+ Should we keep the same namespace? All columns?

In [86]:
features_dir=os.getenv('FEATURES_DATA')
shutil.rmtree(features_dir,ignore_errors=True)
os.makedirs(features_dir)
trans_dd.to_parquet(features_dir,overwrite=True)

# Optional: from Jupyter to Command Line

+ We have drafted our code in a Jupyter Notebook. 
+ Finalized code should be written in Python modules.

## Object Oriented vs Functional Programming

+ We can use classes to keep parameters and functions together.
+ We *could* use Object Oriented Programming, but parallelization of data manipulation and modelling tasks benefit from *Functional Programming*.
+ An Idea: 

    - [Data Oriented Programming](https://blog.klipse.tech/dop/2022/06/22/principles-of-dop.html).
    - Use the class to bundle together parameters and functions.
    - Use stateless operations and treat all data objects as immutable (we do not modify them, we overwrite them).
    - Take advantage of [`@staticmethod`](https://realpython.com/instance-class-and-static-methods-demystified/).

The code is in `./05_src/stock_prices/data_manager.py`.

Our original design was:

![](./images/02_target_pipeline_manager.png)

Download all prices.

Finally, add features to the data set and save to a *feature store*.